### ISSUE TITLE
CLI wrong data improvement

### ISSUE THREAD

**Issue by antonio-fr** [Scille/parsec-cloud#1075]
Parsing of the parsec URL is not done properly.

```
$ parsec core create_organization MYOrg -B parsec://:80 -T 12345
...
assert not hostname.startswith("parsec://")
AttributeError: 'NoneType' object has no attribute 'startswith'

```

I propose to check in the [from_url](https://github.com/Scille/parsec-cloud/blob/0e4e9cb3de402dd551362b07024ac86b3e9711e2/parsec/core/types/backend_address.py#L53) method that the host name is not None or zero-length string.

```
if not split.hostname:
    raise ValueError(f"hostname missing")
```

and eventually combined with isinstance(split.hostname, str)

But worst, the argument are read in an async and weird ways
```
parsec@SRV:~$ parsec core create_organization MYOrg -B parsec://a:80&uname&a -T 12345
[1] 5876
[2] 5877
Linux
a: command not found
[2]+  Done                    uname
Usage: parsec core create_organization [OPTIONS] NAME
Try "parsec core create_organization --help" for help.

Error: Missing option "--administration-token" / "-T".

```
For this point, the only argument is use_ssl, read from the argument no_ssl. So the argument parsing is kind of overkill for a single argument. Plus, the way it is performed with kwargs in class method creation is a very bad security practice. My guess here is that this issue is limited to the user who is running the "core" client, so as he starts the parsec client, he can also run directly the "evil" command elsewhere in his session. Still, a user can execute command from the CLI in the argument of an argument of an option, and this is not so good, as it escape the program boundary, run system command where it is totally not needed.

Normally a URL starts with the protocol to use, and the argument in the data are just a payload. So for the no_ssl case, this should be parsec:// and parsecs:// (parsec over TLS). Or parnotsec:// and parsec://. I know this change has huge impact on the code base, but this will solve this argument parsing in a classy way, there won't be any argument to handle for create_organization. And the call will simply create a BackendAddr with use_ssl True or False (depending of the protocol scheme).

An other way can be to pass the params dictionary in the class creator, and read/decode this dict in the init of the BackendAddr.\__init__ method (creator). Then this creator will read and set the _use_ssl property accordingly. 
Something like this : 
```
class BackendAddr:
    def __init__(self, hostname: str, port: Optional[int] = None, params={}):
        assert not hostname.startswith("parsec://")
        self._hostname = hostname
        self._port, _ = self._parse_port(port, use_ssl)
        self._use_ssl = True
        if "no_ssl" in params and params["no_ssl"]=="true":
            self._use_ssl = False
...
@classmethod
    def from_url(cls, url: str):
    ...
    return cls(hostname=split.hostname, port=split.port, params)
```
I didn't checked at this point if the BackendAddr creator is called with others code parts and what it can break. This is for the idea.

This is also valid for stats_organization and status_organization. In these others CLI commands,  I haven't checked  if the only argument is no_ssl.

**Comment by touilleMan** [comment]
> I propose to check in the from_url method that the host name is not None or zero-length string.

Yep, that's a good idea ;-)

> But worst, the argument are read in an async and weird ways
> parsec@SRV:~$ parsec core create_organization MYOrg -B parsec://a:80&uname&a -T 12345

I don't understand what this command do. My understanding is the `&` symbols make the shell run three commands in parallel:
- `parsec core create_organization MYOrg -B parsec://a:80` which fails because it lacks the `-T` parameter
- `uname` which displays `Linux` and exit
- `a -T 12345` which fails because a is not a valid command

I guess you should do `parsec core create_organization MYOrg -B 'parsec://a:80?uname&a' -T 12345` (note the single quotes) if you want to try providing url with arbitrary parameters

> For this point, the only argument is use_ssl, read from the argument no_ssl. So the argument parsing is kind of overkill for a single argument.

I agree, however this is multiple other url formats in parsec which each has it own set of parameters:
- bootstrap organization: `parsec://parsec.example.com/my_org?action=bootstrap_organization&token=1234ABCD`
- claim user: `parsec://parsec.example.com/my_org?action=claim_user&user_id=John&token=1234ABCD&rvk=P25GRG3XPSZKBEKXYQFBOLERWQNEDY3AO43MVNZCLPXPKN63JRYQssss`
- claim device: `parsec://parsec.example.com/my_org?action=claim_device&device_id=John%40pc&token=1234ABCD&rvk=P25GRG3XPSZKBEKXYQFBOLERWQNEDY3AO43MVNZCLPXPKN63JRYQssss`
- reference a file in a workspace: `parsec://parsec.example.com/my_org?action=file_link&workspace_id=xx&path=yy`

> Plus, the way it is performed with kwargs in class method creation is a very bad security practice.

Can you elaborate ? The kwargs are checked in the `_from_url_parse_and_consume_params` before being used to the untrusted input should have been sanitized:

https://github.com/Scille/parsec-cloud/blob/0e4e9cb3de402dd551362b07024ac86b3e9711e2/parsec/core/types/backend_address.py#L87-L98

> Normally a URL starts with the protocol to use, and the argument in the data are just a payload. So for the no_ssl case, this should be parsec:// and parsecs:// (parsec over TLS).

The decision was to only provide `parsec://` scheme given using TLS is considered as a requirement for a production installation. Hence the `no_ssl` param is just considered as a useful trick for testing only.
On top of that multiple schemes means more schemes to register into the OS (for automatic detection of which application to run when clicking on a link), this is not a big deal in theory but supporting multiple platforms has taught us to stick to simplicity as much as possible ;-)

> Or parnotsec:// and parsec://

I love `parnotsec://` scheme xD

**Comment by antonio-fr** [comment]
Oh sorry, I ignored that the bash interface interprets the command separator "&" even when the argument is stick without any space, it was also same for ksh. Learned it the hard way ;) When I saw the over-complicated argument, I imagined it was the cause of that... Still, I didn't found out why it was the case while reading the *complicated* code. So, there's no issue about this point. And since this protocol change is only for testing, this is fine.
So you just got the hostname checking for a more friendly message than a crash.
