### ISSUE TITLE
Window width of Parsec client in a computer screen

### ISSUE THREAD

**Issue by tleblond** [Scille/parsec-cloud#1162]
Depending the length and the depth of the directory, the width of the Parsec's windows (version 1.13.0) overhead the width of the screen and it is impossible to reduce the size since. This an example :
![image](https://user-images.githubusercontent.com/9845177/82197038-c4d8a600-98fa-11ea-9cd8-aca3271c4391.png)
It would be great to be able to resize the PARSEC's windows taking into account a variable size of police or the shorten of the name of the full directory path name.

**Comment by Max-7** [comment]
Fixed by https://github.com/Scille/parsec-cloud/commit/08cb35111548198a287b4d75d4831fd62491b5da

Not a truly satisfying fix as the path will be cut in an ugly fashion but at least the window will no longer expand and I can't afford to spend too much time on such a minor issue.

Still, it will get a little bit better with #1159 because we'll no longer have to display the mountpoint, which will give us more space for the path.
