### ISSUE TITLE
What happen when receiving a Parsec Link as non connected user

### ISSUE THREAD

**Issue by tleblond** [Scille/parsec-cloud#1167]
When one receive a Parsec link by email  (ex : [Le dossier Oodrive est à cette adresse](parsec://saas.parsec.cloud/Scille-Partnerspace?action=file_link&workspace_id=2807cc03-dc41-4abf-87f8-810a11b54a8f&path=%2FOodrive&no_ssl=true&rvk=EVZMKE5EOZTF2G65W4AH7QQIOAPZ5SCLNEHOC34BBJQ4LGCBC3IAssss).)
If at the time of clicking you are not connected to the organization, Parsec returns the following message:
![image](https://user-images.githubusercontent.com/9845177/83611560-6f9ac680-a581-11ea-84b8-7d8cb2f0ef62.png)
Parsec should manage the following three scenarios:
1) either one is not a member of the organization and then he must receive a clear message telling :
> Vous ne pouvez pas avoir accès à ces données car vous n'êtes pas membre de l'organisation qui la partage / You cannot have access to this data because you are not a member of the organization that shares it
2) either one is a member of the organization but not connected and in this case, one should be automatically sent to a new connection tab
3) either one are connected to the organization and then access the location directly (which is currently the case)

**Comment by Max-7** [comment]
Fixed by https://github.com/Scille/parsec-cloud/commit/f8f7f9e2dfcd26633772e53c181c05c60b683b06

The logic:
- a user has no devices belonging to the organization where the file is located, we display a message telling him so
- a user is not logged in the organization where the file is located, we ask him to log in (and switch to the log in tab if possible)
- a user is logged in the organization but does not have the workspace, we tell him that the workspace was probably not shared with him
- a user is logged in the organization and has the workspace but the file is not found, we tell him that we could not find the file
