### ISSUE TITLE
Rework local storage

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#120]
Need
-----

Stocker les données locales: vlob, block, dirty vlob, dirty block, remote user/device info
Conserver les dirty vlob/block sans limite de temps ni de taille
Une fois synchronisés, supprimer les dirty vlob/block
(bonus) migrer les dirty blocks en block pour éviter des réécritures
Nettoyer les vlobs/blocks non utilisés quand le cache est trop important
(bonus) permettre de spécifier qu'un vlob/block ne doit pas être supprimer pour permettre le mode offline
Les données user/device doivent avoir une durée de vie limitée (~1h) vu que celle-ci peuvent être revoqué à tout instant.

Implementation
----------------

- utilisation de SQlite
- stockage des vlobs directement dans sqlite
- stockage des block sous forme de fichiers (==> vérifier les performances auparavant)
- la table blocks contient la taille de chaque élément + flags (dirty, offline) + date dernier accès + chemin fichier
- on ne prend pas en compte les vlobs ni la base sqlite dans la taille du cache
- vu que les blocks font tous ~ la même taille, on calcule le nb de blocks maximum (via la taille de cache max autorisée)
- garbage collection lazy: si plus de place on remplace le plus vieux blocks

**Comment by frossigneux** [comment]
Un draft ici:
https://github.com/Scille/parsec-cloud/compare/local-storage

**Comment by vxgmichel** [comment]
Decisions for local db strategy after a meeting with @touilleMan :

- Ban copy to avoid file multi-reference on dirty blocks
  *  Multi-reference can still be achieved by moving files to another directory and then reverting the directory. But this should never affect dirty blocks since reverting can only be done on synced directory

- Local db should keep the timestamp for last access to blocks in order to define a garbage collection strategy
  * Warning: keep in mind that a block can be multi-referenced as defined above
  * Question: should vlob be treated differently? (knowing that the vlob can't be multi-referenced)

- Move between workspace have to be treated as a copy: we don't want multi-referencing of blocks across workspaces
  * Why? because the backend history collector should be able to clean a workspace without any knowledge about other workspaces (and without affecting them of course)

**Comment by vxgmichel** [comment]
Rapport d'avancement:

- [x] Stocker les données locales: vlob, block, dirty vlob, dirty block, remote user/device info
   * S'appelle maintenant `remote/local` `block/manifests`, et `user`.
- [x] Conserver les dirty vlob/block sans limite de temps ni de taille
   * Ok: les données locales (i.e. dirty) sont stockés dans des répertoires et base sqlite séparées
- [ ] Une fois synchronisés, supprimer les dirty vlob/block
   * Todo: se produit uniquement sur la suppression pour le moment
- [ ] ~(bonus) migrer les dirty blocks en block pour éviter des réécritures~
   * Finalement non: les dirty blocks doivent être redécoupés avant l'upload 
- [x] Nettoyer les vlobs/blocks non utilisés quand le cache est trop important
   * Ok: reste a décider si on veut un système de "high/low water mark"
- [x] (bonus) permettre de spécifier qu'un vlob/block ne doit pas être supprimer pour permettre le mode offline
   * Ok: il suffit d'utiliser l'api `local` plutot que `remote`
- [x] Les données user/device doivent avoir une durée de vie limitée (~1h) vu que celle-ci peuvent être revoqué à tout instant.
   * Ok: mais non réglable pour le moment

**Comment by touilleMan** [comment]
#221  merged
