### ISSUE TITLE
Make more intuitive the dialog for invinting a device  

### ISSUE THREAD

**Issue by stefan-contiu** [Scille/parsec-cloud#1318]
Currently the dialog lists 3 actions ("Copy Link", "Send Email", "Demarrer"). It's unclear to the users what the actions are supposed to do. In addition, the user is guided to click on "Demarrer", but that's not the first action he/she should click.

I would suggest the following :
1. Put the two buttons "Send Email" and "Copy Link" right after the text "Vous devez echanger...". Put a recommended text under "Send Email". Put "Send Email" at the left of "Copy Link".

2.The button of "Demarrer" might have a better name like "Accueillir". Also the text "Quand vous etre pret..." could be rephrased to enforce that once the procedure is done on the other device.

3. (Optional) could we imagine removing the third button ("Demarrer") and start the listening process immediatly once "Send Email" or "Copy Link" are clicked?

![image](https://user-images.githubusercontent.com/8625772/88777900-12d61980-d188-11ea-98f1-c17f6064a8b9.png)

**Comment by bitlogik** [comment]
Agree, this is not user friendly, and very confusing.

We propose to display in the order of the process : the text "Quand vous êtes prets" below the 2 first buttons.

```

Vous devrez échanger...
| Copier le lien d'invitation |   | Envoyer par email |

Une fois Parsec lancé sur la nouvelle machine, cliquez sur Démarrer ici même
| Démarrer l'enregistrement |
```

One can also imagine to separate the different actions : share code and greet, which can be separated in time : send the invitation, download and install Parsec, then proceed to the onboarding/greeting.
This means having 2 different buttons in My devices :
Invite a new device
Greet a new device
Of course, the modal opened with _Greet new device_ is telling that this is valid for an already invited device.

**Comment by Max-7** [comment]
> This means having 2 different buttons in My devices :
> Invite a new device
> Greet a new device

It was originally thought to be closer to the user invitation, but since you can only invite one device at a time and since the invitation link remains valid as long as you have not gone through the full invitation process, we thought it would be better with only one button.

> 1. (Optional) could we imagine removing the third button ("Demarrer") and start the listening process immediatly once "Send Email" or "Copy Link" are clicked?)

I'm not convinced this would be a good idea, it might get a bit confusing.

What I ended up doing (PR #1334):

If the user is a legacy user (no email available)
![invite_device_no_email](https://user-images.githubusercontent.com/18075498/89164557-8a84b980-d577-11ea-91e1-1319bde8a962.png)

If the user does have an email address
![invite_device_email](https://user-images.githubusercontent.com/18075498/89164546-8789c900-d577-11ea-9b0c-4f8a2d6e9f09.png)
