### ISSUE TITLE
Linux unmount

### ISSUE THREAD

**Issue by bitlogik** [Scille/parsec-cloud#1437]
When unmounting a user storage (logout, unmout query,...), the fusermount binary prints a message and stays in the process list.

Message printed :
`fuse: fuse_remove_signal_handlers: unknown session`

Process list (example) :
_fusermount -o rw,nosuid,nodev,auto_unmount,fsname=FuseOperations -- /home/myuser/guardata/bob_workspace_

To demo watch this issue, best is to click many times un/mount in the GUI, or logout/login many times. In the process list, many fusermount processes would stay.

It is not sure whether these fusermount processes are staying after the GUI closing. Anyway, we think that something wrong happens, at least a warning, when unmounting a drive in Linux, and the process fusermount should not stay in memory.

**Comment by vxgmichel** [comment]
> Message printed :
fuse: fuse_remove_signal_handlers: unknown session

Yes, we're aware of this annoying message and it's been reported to the fuse tracker already: https://github.com/libfuse/libfuse/issues/382.

I don't think it's going to get fixed though.

> Process list (example) :
>    fusermount -o rw,nosuid,nodev,auto_unmount,fsname=FuseOperations -- /home/myuser/guardata/bob_workspace

Oh I wasn't aware of that.. Thanks for letting me know, I'll investigate!

**Comment by vxgmichel** [comment]
> Process list (example) :
> fusermount -o rw,nosuid,nodev,auto_unmount,fsname=FuseOperations -- /home/myuser/guardata/bob_workspace

After a quick investigation, it seems like those processes are related to the `auto_unmount` option (they don't appear if `auto_unmount` is `False`). The `auto_unmount` option is useful because it allows us to make sure the mountpoints are unmounted when the application terminates (even after a crash). I couldn't find any way to terminate those processes when a workspace is successfully unmounted (killing is not an option since they're root processes).

I think the benefits of auto-unmount far outweigh the fact that we're accumulating those zombie processes. I couldn't find an alternative, but let me know if you find something!
