### ISSUE TITLE
Bug with https connexion to a backend allowing only http connexion

### ISSUE THREAD

**Issue by Sithi5** [Scille/parsec-cloud#1583]
![image](https://user-images.githubusercontent.com/39769509/99687536-0fdb9d80-2a85-11eb-9b02-93ce5237ae54.png)

no problem with http :
![image](https://user-images.githubusercontent.com/39769509/99687606-22ee6d80-2a85-11eb-90e5-ddf670456702.png)

Connexion timeout with https :
![image](https://user-images.githubusercontent.com/39769509/99687481-005c5480-2a85-11eb-96d3-2c6c45067e8d.png)

**Comment by touilleMan** [comment]
The issue occurs when running Parsec server without SSL, then trying to initiate an SSL connection to it (remember `parsec://` url are always over ssl unless it has the `no_ssl=true` parameter set)

The issue comes from the fact a SSL handshake starts by the client sending the first frame (i.e. "client Hello") which is not seen as a full first HTTP frame from the server point of view: server is waiting for a `\r\n\r\n` sequence that mark the end of the headers part, if this sequence is not part of the SSL Client Hello then the server is waiting forever for more data.

This "wait for `\r\n\r\n` before doing any parsing" policy comes from h11 (http parsing library used by Parsec server): 

https://github.com/python-hyper/h11/blob/522b00470b5776dda2dc7e98ff778eb1e418e6ad/h11/_readers.py#L70-L81

https://github.com/python-hyper/h11/blob/522b00470b5776dda2dc7e98ff778eb1e418e6ad/h11/_receivebuffer.py#L101-L112

A quick&dirty test on various websites (cowboy, ATS, google server) shows that a `400 Invalid HTTP Request` is returned instead of waiting indefinitely (this most likely comes from a request parsing starting before fully receiving the header part of the http request)

**Comment by touilleMan** [comment]
see https://github.com/python-hyper/h11/issues/121

**Comment by touilleMan** [comment]
Also getting fixed in h11 https://github.com/python-hyper/h11/issues/122

**Comment by touilleMan** [comment]
fixed by #1611
