### ISSUE TITLE
GUI blocked by simultaneous Qt widgets

### ISSUE THREAD

**Issue by Ironicbay** [Scille/parsec-cloud#1786]
Happens on the last window shown after the invitation process, the button is not responsive and requires a force quit.

![IMG-20210517-WA0001](https://user-images.githubusercontent.com/41511029/125760011-ebb053a9-6552-4621-a48c-e59ffe6150b8.jpg)

**Comment by touilleMan** [comment]
related to #1793

**Comment by touilleMan** [comment]
The problem seems to be broader than just macOS.

I think it comes from `Widget.open` which is used in `show_info/error` (cf. https://doc.qt.io/qt-5/qdialog.html#open)

In Qt, opening a modal puts a dialogue widget in the foreground, then blocks any interaction with the other widgets.

In theory there is no concurrency issues with this given the modal is opened with `Widget.exec_` which is a blocking function.

However we use `Widget.open` instead, which is non-blocking (and allow use to create window modal that have the benefit of only blocking a tab instead of the whole GUI)

So we end-up with:
1 - a modal is created, it widget is put on foreground and all other widgets interaction are disabled
2 - a Qt callback is triggered, it put on foreground on another widget

This is typically the kind of behavior that could occurs with the new version check modal at application startup (given the callback depend of an HTTP request that can take any arbitrary time to complete)

I wonder if the issue is not related to the fact we use `Widget.show` in some dialogs (e.g. https://github.com/Scille/parsec-cloud/blob/ab2afdd161f1a2411585fb55fac760aa256ec43f/parsec/core/gui/claim_user_widget.py#L762)
This could be also linked to the manual set of modality in `GreyedDialog.__init__` (However in theory [`setModal` is not supposed to wait for `show` to be called before taking effect](https://doc.qt.io/qt-5/qdialog.html#modal-prop))
https://github.com/Scille/parsec-cloud/blob/ab2afdd161f1a2411585fb55fac760aa256ec43f/parsec/core/gui/custom_dialogs.py#L42-L44


Anyway, to fix this:
1) replace the modal by regular widget (so we would just popup a widget in the foreground, and the user could still interact with the rest of the application). This change should be done with care however given modal is often used as a way to block user interaction.
2) use a global lock on modals so only a single one can be created at a time. This would be very ugly (we are basically doing Qt job doing that...) so I'd rather avoid it
3) make sure we use `Widget.open` instead of `Widget.show` in all `GreyedDialog`. I'm not sure this solution actually work so it is worth to test it a bit before choosing our fix.

**Comment by touilleMan** [comment]
Too old
