### ISSUE TITLE
Make sure parsec creates its config directory if it doesn't exist

### ISSUE THREAD

**Issue by vxgmichel** [Scille/parsec-cloud#2539]
This line from the parsec snap script made me doubt:
https://github.com/Scille/parsec-cloud/blob/5526f2c4e88c00e577c467df6e1089649cd820dc/packaging/snap/bin/parsec#L3

**Comment by Max-7** [comment]
The config folder is created when the `CoreConfig` is initialized (https://github.com/Scille/parsec-cloud/blob/master/parsec/core/config.py#L167). It is in fact better to let the `config_factory` create it because the path may not always be `~` but could depend on the XDG_DATA_HOME env variable (if set) (https://github.com/Scille/parsec-cloud/blob/master/parsec/core/config.py#L34).
