### ISSUE TITLE
[🐛 | Bug]: Changelog format error in 2.13.0-rc2

### ISSUE THREAD

**Issue by Ironicbay** [Scille/parsec-cloud#3266]
### Version

2.13.0-rc2

### What platforms you were running our software when the bug happened ?

MacOS

### What happened ?

<img width="899" alt="Capture d’écran 2022-10-12 à 15 28 03" src="https://user-images.githubusercontent.com/41511029/195356120-cc8cbb35-928d-4db6-85ef-7a0dac9fa42c.png">

**Comment by FirelightFlagboy** [comment]
The bug was introduced in history.rs 151fe7887b676c755fbce62bfa3e1f7060bb4414 but originated from the newsfragment below.

https://github.com/Scille/parsec-cloud/blob/d7efe8d85f47d76bbc204cbb56036d63249247d5/newsfragments/3198.feature.rst

The fragment was created with spaces before each line thus breaking the formatting of the bullet list.

**Comment by FirelightFlagboy** [comment]
The PR #3267 that fix this issue was merged into the branch 2.13
