### ISSUE TITLE
[🐛 Bug] Searchbar should be always visible

### ISSUE THREAD

**Issue by fabienSvtr** [Scille/parsec-cloud#5681]

**Comment by Max-7** [comment]
Tried to fix it, thinking it might be just some HTML tags in the wrong order, but it's more complexe.
The only location where I found it happen was in the workspace sharing modal, but the same problem could appear in all modals.
The problem is, modals handle overflow-y globally by themselves, and I can't find a way to tell them "it's find, I'll handle it myself". Which results in the whole modal being scrollable, instead of just the inner content. It's  very visible in the workspace sharing modal, but we could have a similar problem with other modal if the titles also get included in the scroll.

**Comment by Max-7** [comment]
A similar problem exists with the ChangelogModal. Better to try and find a generic fix.
