### ISSUE TITLE
[rfc-1005] Document On/Off fixup access right

### ISSUE THREAD

**Issue by FirelightFlagboy** [Scille/parsec-cloud#5767]
If a client end up with invalid data:

> An user hasn't started its client in a while, it does it after the Parsec v3 migration
> and now all the workspaces it has been part of that have been re-encrypted in the
> meantime fail to load with an "decryption error" error message...).

To fix this issue, the user need to have its access rights removed then added.

We should document that in a troubleshoot section for the client.

https://github.com/Scille/parsec-cloud/pull/5303/files#r1379898710

**Comment by touilleMan** [comment]
After more thinking, this issue is worst than expected given it may corrupt the initial key rotation:

1) Parsec v2 is in use
2) Alice is OWNER of workspace A
3) Alice share workspace A with Bob (with OWNER role)
4) Alice goes offline
5) Bob reencrypt workspace A
6) Parsec is upgraded to v3
7) Alice goes online (now using a Parsec v3 client), and do the initial key rotation using the workspace key she believe is the last one

Given in Parsec v3, a user (including Alice) decrypts the data from the workspace by getting the key from the keys bundle, they all try to decrypt with the N-1 key data that were encrypted with key N :/

The only way to fix this issue is to have Alice actually ensures it has processed all here messages before doing the initial key rotation.
On top of that, Alice should also try to decrypt the workspace manifest with the key she believe is the right one. This would prevent making the workspace not accessible in the unlikely event the key passed to Alice in the sharing message was corrupted (in Parsec v2 this would also prevent Alice from accessing the workspace, in Parsec v3 break the workspace for all users !).

**Comment by touilleMan** [comment]
v2-to-v3 migration has been dropped, closing.
