### ISSUE TITLE
Templating system for bold text (i18n)

### ISSUE THREAD

**Issue by fabienSvtr** [Scille/parsec-cloud#6236]

**Comment by Max-7** [comment]
It exists in Vue-i18n : https://kazupon.github.io/vue-i18n/guide/interpolation.html#basic-usage

The doc is wrong, you have multiple APIs for that simple thing, and the APIs change every two months. It would not be a `vue-` project otherwise.

You can use a `i18n-t` component (named `i18n` in the doc) with a a prop (`keypath`, named `key` in the doc).

```vue
<template>
  <i18n-t
    keypath="say.hello"
    tag="p"
  >
    <template #name>
      <b>{{ 'Fabien' }}</b>
    </template>
  </i18n-t>
</template>
```

```json
"say": {
  "hello": "Hello {name}!"
}
```

Will get you this:
![Screenshot 2024-01-29 071740](https://github.com/Scille/parsec-cloud/assets/18075498/a9448100-e724-49a6-8d44-3709a1fd81e0)

I've put the string directly (`'Fabien'`) but you can use a variable or some other translation.
