### ISSUE TITLE
Current user can see directories of previous user after uninstall

### ISSUE THREAD

**Issue by stefan-contiu** [Scille/parsec-cloud#715]
Using Ubuntu 18.04.2 LTS :

1. Create a parsec user, add some directories to the mountpoint.
2. Uninstall parsec on client.
3. Re-install using snap.
4. Create a new user and log-in.
5. The mount point displays directories that were created by previous user - security issue.

**Comment by touilleMan** [comment]
The trick is given each workspace gets mountpoint as a separate folder, those folder have the name of their corresponding workspace.
Given those folder cannot be guaranteed to be remove on Parsec shutdown, we could endup leaking those folders.

This should however only occur in case of hard failure (e.g. power shutdown), currently the mounted folder seems to be never deleted even on clean shutdown :'(

The only 100% solution for the folder leaking issue would be to have a single mountpoint per parsec application containing the workpaces (instead of a mountpoint per workspace) (cc @vxgmichel  whith whom we already talked about this approach)
