### ISSUE TITLE
[🐛 | Bug]: Files in the mountpoint seem unacessible during synchronization

### ISSUE THREAD

**Issue by mmmarcos** [Scille/parsec-cloud#7585]
### Parsec version tested on:

3.0.0-b.11

### Platforms tested on:

Linux

### Bug description:

Reported by Thierry: 

1. Copy a directory with files from a mounted workspace in Parsec V2 to a mounted workspace in Parsec V3
2. While copying, files starting to appear with 0 bytes in Parsec V3 mountpoint leading to an error when trying to open.
3. After "some time" files seem to be synchronized and can be open normally.

Is there a way to not display the files if they are not synchronized/accessible?

**Comment by touilleMan** [comment]
After more investigation, the issue comes from two things:
- Reading data from Parsec v2 when the data is not is cache is much slower than reading data from from a regular on-disk filesystem (and on top of that the performance is heavily dependent on the internet connection).
- When the file is under copy, it displayed size (e.g. when doing a `ls -l` on the parent directory) only grows when a flush occurs. A flush can occur if explicitly issued by the application doing the copy (this is not the case here), or automatically if the amount of data written since the last flush is bigger than the blocksize of the file (i.e. 512ko).

The conjunction of those means the file can appear with a size of 0  for quiet some time (while in fact data are being transferred, just at a slow pace that makes reaching the 512ko threshold).

On top of that, opening the file lead to an error... just because the file has not finished to be copied yet !

So in the end I think there is not much to do here: having a really slow copy speed is a corner case, and the whole issue here comes from trying to open a file that is part of an import of multiple files still in progress.
