### ISSUE TITLE
Add freeze information about organization from bindings

### ISSUE THREAD

**Issue by fabienSvtr** [Scille/parsec-cloud#8223]

**Comment by FirelightFlagboy** [comment]
Currently that information is only available to server admin: https://github.com/Scille/parsec-cloud/blob/0d969f52c54eb23a3a7748179f18d62d19ac316d/server/parsec/asgi/administration.py#L185-L210

We don't have a protocol (command) to retrieve the freeze status of an organization, since (says @touilleMan) you will get an error anyway by interacting with the organization

**Comment by FirelightFlagboy** [comment]
The server send an expired organization for that, we don't have a specific event for freeze orga
