### ISSUE TITLE
Remove blob from event payload?

### ISSUE THREAD

**Issue by mmmarcos** [Scille/parsec-cloud#8420]
Follow-up on https://github.com/Scille/parsec-cloud/issues/8410#issuecomment-2355904314 

Given that the blob is not included in the event when its size is greater than `EVENT_VLOB_MAX_BLOB_SIZE`, @vxgmichel suggests that it is not that useful to include it at all, since we cannot rely on its presence in the event to perform some action on it.

**Comment by mmmarcos** [comment]
Any opinion on this @touilleMan?

**Comment by touilleMan** [comment]
The idea behind this field is the fact all client (member of a given realm) connected to the server are going to receive the vlob updated event, then query the server to get the change.

With this field, we eliminate the round-trip which reduce server load on a hot path (given vlob change is considered a frequent occurrence). 

This optimization is not yet implemented on the client side, but should be really trivial since, unlike for certificate, the vlobs are designed to be concurrently modified.
