### ISSUE TITLE
[🐛 | Bug]: Mountpoint not accessible

### ISSUE THREAD

**Issue by Landeers** [Scille/parsec-cloud#8816]
### Parsec version tested on:

3.0.0

### Platforms tested on:

Windows

### Bug description:

https://mantis.dsi.cnrs.fr/view.php?id=92546

We can request an appointment with the person concerned.

### Relevant output:

> Un utilisateur externe ne voit pas le point de montage sur son PC , il voit uniquement le dossier PARSEC, alors que des WS lui sont partagés soit en tant que contributeur soit en tant que lecteur , ce qui ne me semble pas normal.

![image](https://github.com/user-attachments/assets/45d47797-4120-429e-8a8f-9b93ecfac942)

**Comment by mmmarcos** [comment]
A few hints:
- The Parsec item in "Quick links" section is created independently of the creation of the directory. Maybe there was an error when creating the directory?
- If the `C:\Users\CGU\Parsec3` directory is created when mounting a workspace AND there is an error when mounting the workspaces, maybe the error is displayed because there are no mounted workspaces. Could be fixed by creating the directory systematically (instead of waiting first mount)

**Comment by Max-7** [comment]
It's probably due to the fact that the link in the sidebar is added automatically when we start the app, but the folder is only created later when we mount a workspace. So if it's the first time you run the app and you try to access the folder using the sidebar without having logged in once first, you will get this error (I think, not 100% sure but it does make sense).

Check once #8820 has been closed if this error can still occur.

**Comment by vxgmichel** [comment]
This was actually https://github.com/Scille/parsec-cloud/issues/8934 fixed in #https://github.com/Scille/parsec-cloud/pull/8933, right?
There is still https://github.com/Scille/parsec-cloud/issues/8945 open, but I guess we can still close this issue.
Can you confirm @Landeers ?

**Comment by Landeers** [comment]
@vxgmichel This issue has not been reproduce, so we can close it.
