### ISSUE TITLE
Highlight file/folder after clicking on it in the Background tasks menu

### ISSUE THREAD

**Issue by fabienSvtr** [Scille/parsec-cloud#8920]
Simply add the little blue on the item to indicate where it is (scroll to it if necessary)

**Comment by Max-7** [comment]
We already have this feature (it selects instead of adding an overlay). It does seem to have some problem when the folder is currently opened though.

As for the "scroll to it if necessary", https://github.com/Scille/parsec-cloud/pull/8627 but it's a draft right now, I have some troubles making it work.
