### ISSUE TITLE
[🐛 | Bug]: Synced file visible only after F5

### ISSUE THREAD

**Issue by NicoTuxx** [Scille/parsec-cloud#9002]
### Parsec version tested on:

3.2.0

### Platforms tested on:

Linux

### Bug description:

User A shared a file to User B.
When showed as "synced" for User A, User B needed to trigger "F5" to actually see the file.

**Comment by mmmarcos** [comment]
I've noticed this problem, but it's not systematic:

- 1 org with 2 users: an Admin on Linux, a Standard on Windows (VM)
- A workspace is shared between the two users.
- User on Linux imports a file on the workspace
- User on Windows
  - **OK** Sees the file appears almost instantly in the File Explorer (Windows)
  - **KO** Does not see the file appears in Parsec GUI (need to change page and come back to the workspace)

After that, I tested by importing a file on Windows. The file appears instantly on both file explorer (Linux) and Parsec GUI **OK**.

After that, tested again the first procedure and the file appeared instantly in both File Explorer (Windows) and Parsec GUI. So I don't know how to reproduce it systematically.

**Comment by touilleMan** [comment]
I could reproduce the issue with @Landeers 

- Organization on the trial SAAS
- Linux client
- Parsec 3.2 (Snap version) and master branch

Steps:
1. on a shared workspace, user 1 creates a folder
2. user 2 goes into the new folder in the Parsec GUI
3. user 1 copies multiple files (~3, each with a size around 60ko to 2.5mo) from within Parsec GUI by using drap&drop (user 1 is on Windows)
4. a) user 2 sometime sees only a subset of the copied files (in this case a simple refresh is enough to see the full content of the folder)
   b) user 2 sometime doesn't see any copied files (i.e. the folder appears still empty).

Case 4.a) and 4.b) are most likely uncorrelated bug

## case 4.a

My guess is this is due to the GUI refreshing the folder early on, and at that time some of the folder's children are not synchronized yet.
In theory is this okay since once synchronized, the missing children should trigger an event in libparsec that notify the GUI the folder content has changed... but for whatever reason this is not happening (or the GUI dismiss the event, maybe because it is currently refreshing the folder when receiving the event ?)

## case 4.b

This is the more concerning bug.

In this case the folder on the mountpoint appears also empty, and the mountpoint itself starts hanging (i.e. switching to another location in the mountpoint makes the file explorer spin forever with a "loading..." message)

In the GUI:
- it is still possible to navigate in the folders as long as such folder is in local cache
- if a folder is not in the cache, navigating into it displays forever the "loading the folder..." message
- Creating a new folder or renaming an existing item does nothing
- Log out hangs forever with the "Logging out. Please wait..." message

Quitting Parsec is still possible however, bu the mountpoint stays present (and accessing it obsiously creates a "transport endpoint is not connected" error.

Once restarted, everything is works fine.

**Comment by Max-7** [comment]
A little description of the GUI behavior:
1. It lists a folder and places a watcher on the current path
2. It waits for `WorkspaceWatchedEntryChanged` events and triggers an internal event (https://github.com/Scille/parsec-cloud/blob/3d97fa4a86c8952224f25189c138cb126acc4329/client/src/parsec/login.ts#L221)
3. Events of this type are aggregated, meaning they will be dispatched only after 1000ms without receiving another event. This is done to avoid too much refreshing
4. On receiving this event, the current folder is refreshed https://github.com/Scille/parsec-cloud/blob/3d97fa4a86c8952224f25189c138cb126acc4329/client/src/views/files/FoldersPage.vue#L448C6-L448C35

Most of the time, this should only result in, at worst, the GUI refreshing too much. The only case where we would not refresh is if we had multiple `WorkspaceWatchedEntryChanged` with an interval less than 1000ms between them for a very long time, which does seem a bit unlikely.
