### ISSUE TITLE
Default rights on mountpoint

### ISSUE THREAD

**Issue by Max-7** [Scille/parsec-cloud#940]
Currently the mountpoint has 755 rights on it, which allows a user on the same machine to see files contained in the mountpoint if Parsec is started.

**Comment by bitlogik** [comment]
The mounted method is now a file system disk. How is the new method is affected by this issue? Can other users on the machine can still see the file in the Parsec disk?
It can be OK if the disk mountpoint is unmounted on session closing, if we assume an other user required the current user to leave her session.

What about Linux?

**Comment by vxgmichel** [comment]
> The mounted method is now a file system disk.

Only on windows actually, the system remained the same as before on linux.

> Can other users on the machine can still see the file in the Parsec disk?

This would have to be double checked but the parsec drives on windows should only be available to the user who mount them.

> What about Linux?

This issue is specifically about linux. This would be easy to fix by simply changing the default rights for the parsec directory and the workspace files and directories, but it's part of a broader issue about file attributes:
- Should we allow a user the change the rights for files and directories within a workspace?
- In this case, should those rights be synchronized with other clients?

**Comment by bitlogik** [comment]
Setting 700 mode for the mounted files on Linux is OK for this issue. The exact issue is "755 on the mountpoint" on Linux (we didn't get it was only Linux related).

Beyond this, in which case a user would need to change the rights for files and directories within a workspace? If there's no reason, this new capability is not needed.

**Comment by vxgmichel** [comment]
> Beyond this, in which case a user would need to change the rights for files and directories within a workspace? If there's no reason, this new capability is not needed.

A good example of that is execution rights. It sounds like a good idead to have file in `500` mode by default but let a user do `chmod +x myfile` if they one want to execute it.
