### ISSUE TITLE
Performing a memory dump after logging out from Parsec should not leak secret keys

### ISSUE THREAD

**Issue by stefan-contiu** [Scille/parsec-cloud#968]
This potential problem was mentioned by OPIDA, the certification company contracted for the ANSSI CSPN.

**Comment by c4ffein** [comment]
We planned to change the system to one password for all users, which limits the interest of this issue. We still have to trust the device we are running on, and we can't do cleanup of specific memory section with a high level language like Python. Hence the interest of this issue is actually limited considering our threat model
